FROM python:3.10-alpine

COPY requirements.txt /app/

WORKDIR /app

RUN pip install -r requirements.txt

COPY . /app

ENV FLASK_ENV=development

EXPOSE 5000

ARG VERSION=1.0.0
ENV APP_VERSION=${VERSION}

ENTRYPOINT ["flask", "run", "-h", "0.0.0.0"]
