FROM python:3.10-slim
RUN apt-get update && apt-get install -y \
 curl \
  && rm -rf /var/lib/apt/lists/*
  
COPY requirements.txt /app/

WORKDIR /app

RUN pip install -r requirements.txt

COPY . /app

ENV FLASK_ENV=development

EXPOSE 5000

ENTRYPOINT ["flask", "run", "-h", "0.0.0.0"]
