FROM python:3.10-alpine

COPY requirements.txt /app/

WORKDIR /app

# we need a bunch dependencies to build the psycopg2 package, but we don't them need to run it afterwards
RUN \
    apk add --no-cache --virtual .build gcc python3-dev musl-dev postgresql-dev && \
    pip install --no-cache-dir -r requirements.txt && \
    apk del --no-cache .build

RUN apk add --no-cache postgresql-libs

COPY . /app

ENV FLASK_ENV=development

EXPOSE 5000

ARG VERSION=1.0.0
ENV APP_VERSION=${VERSION}

ENTRYPOINT ["flask", "run", "-h", "0.0.0.0"]
