apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
        - image: ghcr.io/eficode-academy/quotes-flask-backend:{{ .Values.backend.tag }}
          name: quotes-flask-backend
          ports:
            - containerPort: 5000
          resources: {}
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret
status: {}
