apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      containers:
        - image: ghcr.io/eficode-academy/quotes-flask-frontend:{{ .Values.frontend.tag }}
          name: quotes-flask-frontend
          ports:
            - containerPort: 5000
          resources: {}
          env:
            # load namespace from downward api
            # https://github.com/kubernetes/kubernetes/blob/release-1.0/docs/user-guide/downward-api.md
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: BACKEND_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: backend_host
            - name: BACKEND_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: backend_port

status: {}
