apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:14.3
          name: postgres
          ports:
            - containerPort: 5432
          resources: {}
          ### Using hardcoded env vars
          # env:
          # - name: POSTGRES_USER
          # value: superuser
          # - name: POSTGRES_PASSWORD
          # value: complicated
          # - name: POSTGRES_DB
          # value: quotes
          ### using configMapKeyRef
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: db_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: db_password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: db_name
status: {}
